language: shell
version: ~> 1.0
os:
    - linux
cache:
    apt: true
dist: xenial
addons:
    apt:
        packages:
            - shellcheck
notifications:
  email:
    on_success: change 
    on_failure: always 
script:
    - shellcheck -e SC1090,SC1091,SC2103 -s sh spec*.sh *.config

